version: 0.2 
        
phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    on-failure: ABORT
    commands:
      - echo "Starting SAM packaging `date` in `pwd`"
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yaml
  post_build:
    commands:
      - echo "SAM packaging completed on `date`"

artifacts: # https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec.artifacts
  files:
    - packaged.yaml
    # - location
  name: artifact-name
  discard-paths: yes